const fs = require('fs')
const path = require('path')
const src = path.join(__dirname, '..', '..', 'Flexibank')
const dest = path.join(src, 'archived_html')
if (!fs.existsSync(dest)) fs.mkdirSync(dest)
const files = fs.readdirSync(src).filter(f => f.endsWith('.html'))
files.forEach(f => {
  fs.renameSync(path.join(src, f), path.join(dest, f))
  console.log('Moved', f)
})
console.log('Moved', files.length, 'files to', dest)
